apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:5.6.3
        name: kibana
        env:
        - name: CLUSTER_NAME
          value: "docker-cluster"
        - name: ELASTIC_SEARCH_URL
          value: "http://elasticsearch:9200"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_ML_ENABLED
          value: "false"
        - name: XPACK_GRAPH_ENABLED
          value: "false"
        - name: XPACK_REPORTING_ENABLED
          value: "false"
        - name: XPACK_GROKDEBUGGER_ENABLED
          value: "false"
        ports:
        - containerPort: 5601
