apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: PATH_CONFIG
          value: "/usr/share/logstash/pipeline"
        - name: HTTP_HOST
          value: "0.0.0.0"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: docker.elastic.co/logstash/logstash:5.6.3
        name: logstash
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: pipeline
      volumes:
      - name: pipeline
        hostPath:
            path: /Users/pritamkadam/TMT/elk/docker-elk/k8s/logstash/pipeline/
